<br/><br/><br/>
<div class="center title bold">Choose the option you want:</div>
<br/>
<div class="center">
	- <a href="<?php echo $this->url(array('controller'=>'index','action'=>'edit'), null, false); ?>">Edit Profile</a><br/>
	- <a href="<?php echo $this->url(array('controller'=>'index','action'=>'message'), null, false); ?>">Messages</a><br/>
	- <a href="<?php echo $this->url(array('controller'=>'index','action'=>'csv'), null, false); ?>">CSV Editing</a><br/>
</div>